package pgsql

const (
	//
	FunctionASPHarness             Identifier = "asp_harness"
	FunctionIntArrayUnique         Identifier = "uniq"
	FunctionIntArraySort           Identifier = "sort"
	FunctionJSONBToTextArray       Identifier = "jsonb_to_text_array"
	FunctionJSONBArrayElementsText Identifier = "jsonb_array_elements_text"
	FunctionJSONBBuildObject       Identifier = "jsonb_build_object"
	FunctionJSONBArrayLength       Identifier = "jsonb_array_length"
	FunctionArrayLength            Identifier = "array_length"
	FunctionArrayAggregate         Identifier = "array_agg"
	FunctionMin                    Identifier = "min"
	FunctionMax                    Identifier = "max"
	FunctionLocalTimestamp         Identifier = "localtimestamp"
	FunctionLocalTime              Identifier = "localtime"
	FunctionCurrentTime            Identifier = "current_time"
	FunctionCurrentDate            Identifier = "current_date"
	FunctionNow                    Identifier = "now"
	FunctionToLower                Identifier = "lower"
	FunctionToUpper                Identifier = "upper"
	FunctionCoalesce               Identifier = "coalesce"
	FunctionUnnest                 Identifier = "unnest"
	FunctionJSONBSet               Identifier = "jsonb_set"
	FunctionCount                  Identifier = "count"
	FunctionStringToArray          Identifier = "string_to_array"
	FunctionEdgesToPath            Identifier = "edges_to_path"
	FunctionExtract                Identifier = "extract"
)